# Dockerfile for backend

# Install necessary packages for mysqlclient
RUN apt-get update && \
    apt-get install -y build-essential libmariadb-dev pkg-config && \
    apt-get clean

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
