# Dockerfile.frontend

# Use the official Node.js 18-alpine image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port where the app will run
EXPOSE 8080

# Start the npm development server
CMD ["npm", "run", "serve"]
